# Generated by Django 4.1.5 on 2023-02-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contant_number',
            field=models.IntegerField(),
        ),
    ]
